services:
  redis-master:
    container_name: ${PROJECT_NAME}-redis
    hostname: "redis"
    image: redis:${REDIS_VERSION}
    ports:
      - "6379:6379"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
